language: java
sudo: false
dist: trusty

refs:
  - &bundle
    stage: bundle
    script:
      - ant

  - &bench
    stage: benchmark
    script:
      - ant
      - java -jar out/jars/app.jar --list >list.txt
      - 'for PROP in `cat list.txt`; do java -jar out/jars/app.jar "$PROP" || exit 1; done'

jobs:
  include:
    - stage: "Basic checks"
      name: "Print properties"
      script:
        - ant print-properties
        - ant example
    - stage: "Basic checks"
      name: "version.txt is up to date"
      script:
        - ant
        - java -jar out/jars/app.jar --update-version && git diff --quiet --exit-code -- version.txt

#    - <<: *bundle
#      os: osx
#    - <<: *bundle
#      jdk: openjdk7
#    - <<: *bundle
#      jdk: openjdk8
#    - <<: *bundle
#      jdk: oraclejdk8
#    - <<: *bundle
#      jdk: oraclejdk9
#    - <<: *bundle
#      jdk: oraclejdk11

#    - <<: *bench
#      os: osx
#    - <<: *bench
#      jdk: openjdk8
#    - <<: *bench
#      jdk: oraclejdk11
    - <<: *bench
      os: windows
      language: shell

stages:
  - "Basic checks"
  - bundle
  - benchmark

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'
  - 'if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install jre8 jdk8 ant --ignore-dependencies --install-arguments="/l*v c:/jre8_msi_install.log"; cat c:/jre8_msi_install.log; fi'
