sudo: false
dist: trusty
language: java

jobs:
  include:

    - &show
      stage: show
      jdk: openjdk8
      script:
        - ant
        - 'java -jar out/jars/app.jar "$PROPERTY"'

    - &compile
      stage: compile
      script:
        - ant
        - ant example

    - <<: *compile
      jdk: openjdk7
    - <<: *compile
      jdk: openjdk8

    - <<: *show
      env: PROPERTY=java.vm.name
    - <<: *show
      env: PROPERTY=java.vm.vendor

stages:
  - compile
  - show

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'
