language: java
sudo: false
dist: trusty

refs:
  - &bundle
    stage: bundle
    script:
      - java -version
      - javac -version
      - ant
      - 'mkdir -p "$HOME/.prebuilt"'
      - 'ls "$HOME/.prebuilt"'
      - 'rm -rf "$HOME/.prebuilt"/*.jar'
      - 'cp out/jars/app.jar "$HOME/.prebuilt/"`git rev-parse HEAD`.jar'

  - &bench
    stage: benchmark
    script:
      - java -version
      - mkdir -p out/jars/
      - CACHED_JAR_NAME="$HOME/.prebuilt/"`git rev-parse HEAD`.jar; if [ -e "$CACHED_JAR_NAME" ]; then cp "$CACHED_JAR_NAME" out/jars/app.jar; else ant; fi
      - java -jar out/jars/app.jar --list >list.txt
      - 'for PROP in `cat list.txt`; do java -jar out/jars/app.jar "$PROP" || exit 1; done'

jobs:
  include:
    - stage: "Basic checks"
      name: "Print properties"
      script:
        - ant print-properties
        - ant example
    - stage: "Basic checks"
      name: "System info"
      script:
        - uname -a
        - lscpu
        - free -h
        - df -h
    - stage: "Basic checks"
      name: "version.txt is up to date"
      script:
        - ant
        - java -jar out/jars/app.jar --update-version && git diff --quiet --exit-code -- version.txt

    - <<: *bundle
      os: osx
      env:
        - USE_JDK=OpenJDK-11
#    - <<: *bundle
#      jdk: openjdk7
#    - <<: *bundle
#      jdk: openjdk8
#    - <<: *bundle
#      jdk: oraclejdk8
#    - <<: *bundle
#      jdk: oraclejdk9
    - <<: *bundle
      jdk: oraclejdk11
    - <<: *bundle
      env:
        - USE_JDK=OpenJ9

    - <<: *bench
      os: osx
      env:
        - USE_JDK=OpenJDK-11
#    - <<: *bench
#      jdk: openjdk8
    - <<: *bench
      jdk: oraclejdk11
    - <<: *bench
      env:
        - USE_JDK=OpenJ9
#    - <<: *bench
#      os: windows
#      language: shell

stages:
  - "Basic checks"
  - bundle
  - benchmark

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'
  - 'if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install jre8 --install-arguments="/l*v c:/jre8_msi_install.log"; cat c:/jre8_msi_install.log; fi'

before_script:
  - "# Install custom JDK if needed"
  - 'if [ -n "$USE_JDK" ]; then wget "https://github.com/sormuras/bach/raw/master/install-jdk.sh" && chmod +x install-jdk.sh; fi'
  - 'if [ -n "$USE_JDK" ]; then export JAVA_HOME="$HOME/$USE_JDK"; fi'
  - 'if [ "$USE_JDK" = "OpenJ9" ]; then ./install-jdk.sh --url "https://api.adoptopenjdk.net/v2/binary/releases/openjdk11?openjdk_impl=openj9&os=linux&arch=x64&release=latest&heap_size=normal&type=jdk" --target "$JAVA_HOME"; fi'
  - 'if [ "$USE_JDK" = "OpenJDK-11" ]; then ./install-jdk.sh --feature 11 --target "$JAVA_HOME"; fi'
  - 'if [ -n "$USE_JDK" ]; then export PATH="$JAVA_HOME/bin:$PATH"; fi'

cache:
  directories:
    - $HOME/.prebuilt/
