sudo: false
dist: trusty
language: java

os:
  - linux
#  - osx

jdk:
#  - oraclejdk8
#  - oraclejdk9
#  - oraclejdk11
  - openjdk7
  - openjdk8

jobs:
  include:
    - stage: test
      jdk:
        - openjdk7
        - openjdk8
      script:
        - ant
        - ant example
    - stage: show
      jdk: openjdk8
      env:
        - COMPILE_ONLY=true
        - PROPERTY=java.vm.name
        - PROPERTY=java.vm.vendor
      script:
        - ant
        - 'if [ -n "$PROPERTY" ]; then java -jar out/jars/app.jar "$PROPERTY"; fi'

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'
