sudo: false
dist: trusty
language: java

refs:
  - &bundle
    stage: bundle
    script:
      - ant
  - &bench
    stage: benchmark
    jdk: openjdk8
    script:
      - ant
      - 'java -jar out/jars/app.jar "$PROPERTY"'

jobs:
  include:
    - stage: "Basic checks"
      script:
        - ant print-properties
        - ant example

    - <<: *bundle
      os: osx
    - <<: *bundle
      jdk: openjdk7
    - <<: *bundle
      jdk: openjdk8
    - <<: *bundle
      jdk: oraclejdk8
    - <<: *bundle
      jdk: oraclejdk9
    - <<: *bundle
      jdk: oraclejdk11

    - <<: *bench
      env: PROPERTY=java.vm.name
      os: osx
    - <<: *bench
      env: PROPERTY=java.vm.name
    - <<: *bench
      env: PROPERTY=java.vm.vendor

stages:
  - "Basic checks"
  - bundle
  - benchmark

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'
