language: java
sudo: false
dist: trusty

refs:
  - &bundle
    stage: bundle
    script:
      - ant

  - &bench
    stage: benchmark
    script:
      - ant
      - java -jar out/jars/app.jar --list >list.txt
      - 'for PROP in `cat list.txt`; do java -jar out/jars/app.jar "$PROP"; done'

jobs:
  include:
    - stage: "Basic checks"
      script:
        - ant print-properties
        - ant example

#    - <<: *bundle
#      os: osx
    - <<: *bundle
      jdk: openjdk7
    - <<: *bundle
      jdk: openjdk8
    - <<: *bundle
      jdk: oraclejdk8
    - <<: *bundle
      jdk: oraclejdk9
    - <<: *bundle
      jdk: oraclejdk11

#    - <<: *bench
#      os: osx
    - <<: *bench
      jdk: openjdk8
    - <<: *bench
      jdk: oraclejdk11
    - <<: *bench
      os: windows
      language: shell

stages:
  - "Basic checks"
  - bundle
  - benchmark

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'
  - 'if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install openjdk ant; fi'
