sudo: false
dist: trusty
language: java

refs:
  - &compile
    stage: compile
    name: Bundling
    script:
      - ant
      - ant example
  - &show
    stage: show
    name: Demo
    jdk: openjdk8
    script:
      - ant
      - 'java -jar out/jars/app.jar "$PROPERTY"'

jobs:
  include:
    - stage: prepare
      name: "Set-up"
      script:
        - ant print-properties

    - <<: *compile
      os: osx
    - <<: *compile
      jdk: openjdk7
    - <<: *compile
      jdk: openjdk8
    - <<: *compile
      jdk: oraclejdk8
    - <<: *compile
      jdk: oraclejdk9
    - <<: *compile
      jdk: oraclejdk11

    - <<: *show
      env: PROPERTY=java.vm.name
      os: osx
    - <<: *show
      env: PROPERTY=java.vm.name
    - <<: *show
      env: PROPERTY=java.vm.vendor

stages:
  - prepare
  - compile
  - show

addons:
  apt:
    packages:
      - ant-optional

before_install:
  - 'if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install ant; fi'
